debug:
  datatype: mysql
  hostname: localhost
  database: test
  username: root
  password: root

test:
  datatype: mysql
  hostname: localhost
  database: test
  username: root
  password: root

release:
  datatype: mysql
  hostname: localhost
  database: test
  username: root
  password: root